"""Initial database schema with warehouses, zones, inventory, allocations, and reports

Revision ID: 5a77290a6d77
Revises: 
Create Date: 2025-12-12 17:45:19.943458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a77290a6d77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_name', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('site2', sa.String(length=255), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bsf_factor', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('upload_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=True)

    op.create_table('allocation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('result_name', sa.String(length=255), nullable=True),
    sa.Column('bsf_factor', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('total_allocated', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('overall_fit', sa.Boolean(), nullable=True),
    sa.Column('allocation_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['inventory_uploads.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('length', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('psf', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('service_branch', sa.String(length=50), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('requires_climate_control', sa.Boolean(), nullable=True),
    sa.Column('requires_special_handling', sa.Boolean(), nullable=True),
    sa.Column('item_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['inventory_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index('idx_upload_category', ['upload_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_upload_id'), ['upload_id'], unique=False)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_order', sa.Integer(), nullable=True),
    sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('strength', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('climate_controlled', sa.Boolean(), nullable=True),
    sa.Column('temperature_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('special_handling', sa.Boolean(), nullable=True),
    sa.Column('container_capacity', sa.Integer(), nullable=True),
    sa.Column('is_weather_zone', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_reports')
    op.drop_table('zones')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_upload_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_category'))
        batch_op.drop_index('idx_upload_category')

    op.drop_table('inventory_items')
    op.drop_table('allocation_results')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))

    op.drop_table('warehouses')
    op.drop_table('inventory_uploads')
    # ### end Alembic commands ###
